### ISSUE TITLE
[Bug] ignoreCollapsibleUi does not work

### ISSUE THREAD

**Issue by sectsect** [Onset/inner-vh#2]
Thanks for useful package.

The option `ignoreCollapsibleUi` is not working.
I'd be grateful if you could sort this issue.

Thanks in advance.

**Comment by FilipChalupa** [comment]
I've just checked and I believe it is is working as supposed to. I've tested google chrome on android.

Beware that `ignoreCollapsibleUi` defaults to `true` and `maximumCollapsibleUiHeight` defaults to `100` so browser resizes smaller than `100px` are ignored, don't cause custom property to recalculate. 100 is slightly more than url box height.

Experiment/demo: https://imgur.com/a/Sf01yXs

Can you tell me more about your use case. What is not working as you expect?

**Comment by sectsect** [comment]
@FilipChalupa 

Thanks for your checking.

Sorry. I was wrong.
The option `maximumCollapsibleUiHeight` helped me.

Thank you so much.

**Comment by FilipChalupa** [comment]
Do you know about a browser which has collapsible ui higher than 100. Which one is it please so I can adjust the default value of `maximumCollapsibleUiHeight`. If I understand you correctly there is one which doesn't fit the limit.

**Comment by sectsect** [comment]
@FilipChalupa 

Thank you.
I didn't understand enough.
